/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdIndexRouteImport } from './routes/$id.index'
import { Route as IdEditRouteImport } from './routes/$id.edit'
import { Route as IdCopyRouteImport } from './routes/$id.copy'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdRoute,
} as any)
const IdEditRoute = IdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => IdRoute,
} as any)
const IdCopyRoute = IdCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => IdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/$id': typeof IdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id' | '/new' | '/$id/copy' | '/$id/edit' | '/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/$id/copy' | '/$id/edit' | '/$id'
  id: '__root__' | '/' | '/$id' | '/new' | '/$id/copy' | '/$id/edit' | '/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRouteWithChildren
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/edit': {
      id: '/$id/edit'
      path: '/edit'
      fullPath: '/$id/edit'
      preLoaderRoute: typeof IdEditRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/copy': {
      id: '/$id/copy'
      path: '/copy'
      fullPath: '/$id/copy'
      preLoaderRoute: typeof IdCopyRouteImport
      parentRoute: typeof IdRoute
    }
  }
}

interface IdRouteChildren {
  IdCopyRoute: typeof IdCopyRoute
  IdEditRoute: typeof IdEditRoute
  IdIndexRoute: typeof IdIndexRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdCopyRoute: IdCopyRoute,
  IdEditRoute: IdEditRoute,
  IdIndexRoute: IdIndexRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRouteWithChildren,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
