/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdIndexRouteImport } from './routes/$id.index'
import { Route as ApiConfigsRouteImport } from './routes/api.configs'
import { Route as IdEditRouteImport } from './routes/$id.edit'
import { Route as IdCopyRouteImport } from './routes/$id.copy'
import { Route as ApiConfigsIdRouteImport } from './routes/api.configs.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdRoute,
} as any)
const ApiConfigsRoute = ApiConfigsRouteImport.update({
  id: '/api/configs',
  path: '/api/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const IdEditRoute = IdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => IdRoute,
} as any)
const IdCopyRoute = IdCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => IdRoute,
} as any)
const ApiConfigsIdRoute = ApiConfigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConfigsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/api/configs': typeof ApiConfigsRouteWithChildren
  '/$id/': typeof IdIndexRoute
  '/api/configs/$id': typeof ApiConfigsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/api/configs': typeof ApiConfigsRouteWithChildren
  '/$id': typeof IdIndexRoute
  '/api/configs/$id': typeof ApiConfigsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/new': typeof NewRoute
  '/$id/copy': typeof IdCopyRoute
  '/$id/edit': typeof IdEditRoute
  '/api/configs': typeof ApiConfigsRouteWithChildren
  '/$id/': typeof IdIndexRoute
  '/api/configs/$id': typeof ApiConfigsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/new'
    | '/$id/copy'
    | '/$id/edit'
    | '/api/configs'
    | '/$id/'
    | '/api/configs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/$id/copy'
    | '/$id/edit'
    | '/api/configs'
    | '/$id'
    | '/api/configs/$id'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/new'
    | '/$id/copy'
    | '/$id/edit'
    | '/api/configs'
    | '/$id/'
    | '/api/configs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRouteWithChildren
  NewRoute: typeof NewRoute
  ApiConfigsRoute: typeof ApiConfigsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof IdRoute
    }
    '/api/configs': {
      id: '/api/configs'
      path: '/api/configs'
      fullPath: '/api/configs'
      preLoaderRoute: typeof ApiConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/edit': {
      id: '/$id/edit'
      path: '/edit'
      fullPath: '/$id/edit'
      preLoaderRoute: typeof IdEditRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/copy': {
      id: '/$id/copy'
      path: '/copy'
      fullPath: '/$id/copy'
      preLoaderRoute: typeof IdCopyRouteImport
      parentRoute: typeof IdRoute
    }
    '/api/configs/$id': {
      id: '/api/configs/$id'
      path: '/$id'
      fullPath: '/api/configs/$id'
      preLoaderRoute: typeof ApiConfigsIdRouteImport
      parentRoute: typeof ApiConfigsRoute
    }
  }
}

interface IdRouteChildren {
  IdCopyRoute: typeof IdCopyRoute
  IdEditRoute: typeof IdEditRoute
  IdIndexRoute: typeof IdIndexRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdCopyRoute: IdCopyRoute,
  IdEditRoute: IdEditRoute,
  IdIndexRoute: IdIndexRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

interface ApiConfigsRouteChildren {
  ApiConfigsIdRoute: typeof ApiConfigsIdRoute
}

const ApiConfigsRouteChildren: ApiConfigsRouteChildren = {
  ApiConfigsIdRoute: ApiConfigsIdRoute,
}

const ApiConfigsRouteWithChildren = ApiConfigsRoute._addFileChildren(
  ApiConfigsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRouteWithChildren,
  NewRoute: NewRoute,
  ApiConfigsRoute: ApiConfigsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
